---
title: "Well-being of Individuals from the United States Global Social Survey are Affected by Finances, Relationships, and Health"
author: "Justin Abando, Jin Di Liu, Marcin Jaczynski"
thanks: "Code and data are available at: https://github.com/jackchinski/happiness_report"
date: "`r Sys.time()`"
date-format: "D MMMM YYYY"
abstract: "DON'T FORGET THIS"
format: pdf
bibliography: references.bib
---

```{r}
#| include: false

knitr::opts_chunk$set(echo=TRUE)

###Workplace Setup###
library(tidyverse)
library(dplyr)
library(ggplot2)
library(gtsummary)
library(flextable)

quartoclean5 <- read_csv("../../inputs/data/clean5.csv")
mastercleaned <-read_csv("../../outputs/data/master_cleaned.csv")
happycleaned <- read_csv("../../outputs/data/happy_cleaned.csv")
finaltercleaned <-read_csv("../../outputs/data/finalter_cleaned.csv")
hapmarcleaned <- read_csv("../../outputs/data/hapmar_cleaned.csv")
healthcleaned <- read_csv("../../outputs/data/health_cleaned.csv")

```



# 1 Introduction


# 2 Data


## 2.1 Tools Used



## 2.2 Survey Methodology



## 2.3 Survey Biases and Ethics



## 2.4 Data Collection



## 2.5 Data Cleaning



# 3 Results

\newpage
```{r}
#| label: table-satfinincome
#| tbl-cap: Table Visualization of financial satisfaction of respondents with respect to their relative income. There is a larger proportion of respondents that claim that they are not satisfied with their finances at lower income ranges. As the income range increases, more respondents proportionally express that they are either more of less satisfied, or are pretty well satisfied with their financial situation.
#| echo: false
#| message: false
table_satfinincome <- mastercleaned %>% 
  tbl_cross(row = satfin, col = new_income_range, label = list(new_income_range ~ "Income Ranges", satfin ~ "Finances"), percent = "column") %>% as_flex_table() %>% set_caption(caption = "Financial Satisfaction vs. Income Ranges")

table_satfinincome %>%

```

```{r}
#| label: fig-satfincome
#| fig-cap: Visualization of financial satisfaction of respondents with respect to their relative income. There is a larger proportion of respondents that claim that they are not satisfied with their finances at lower income ranges. As the income range increases, more respondents proportionally express that they are either more of less satisfied, or are pretty well satisfied with their financial situation.
#| echo: false
ggplot( 
  mastercleaned, aes(
    x = new_income_range, fill = satfin)) + 
  geom_bar(
    position = "stack") + #Creating a stacked bar plot
  theme_minimal() + #Using a simple theme
  theme(axis.text.x=element_text( #Adjusting horizontal axis text to be easily readable
    angle = 60, 
    hjust = 1)) + 
  labs(x = "Income Ranges", #Labeling the axes and fill section
       y = "Frequency",
       fill = "Financial Satisfaction")

```

\newpage
```{r}
#| label: table-happyandsatfin
#| fig-cap: something
#| echo: false
#| message: false
happycleaned %>% 
  tbl_cross(row = happy, col = satfin, label = list(satfin ~ "Financial Satisfactions", happy ~ "Happiness"), percent = "column")
```
```{r}
#| label: table-happyandincomes
#| fig-cap: something2
#| echo: false
#| message: false
happycleaned %>% 
  tbl_cross(row = happy, col = new_income_range, label = list(new_income_range ~ "Income Ranges", happy ~ "Happiness"), percent = "column")
```

\newpage

```{r}
#| label: fig-satfinhappy
#| fig-cap: something3
#| echo: false

ggplot(
  happycleaned, aes(
    x = satfin, fill = happy)) + 
  geom_bar(
    position = "stack") + #Creating a stacked bar plot
  theme_minimal() + #Using a simple theme
  theme(axis.text.x=element_text( #Adjusting horizontal axis text to be easily readable
    angle = 60, 
    hjust = 1)) + 
  labs(x = "Financial Satisfaction", #Labeling the axes and fill section
       y = "Frequency",
       fill = "Happiness Response")+
  scale_x_discrete(limit = c("Not satisfied at all", "More or less satisfied", "Pretty well satisfied"))

```
\newpage

```{r}
#| label: fig-happyincome
#| fig-cap: ???
#| echo: false

ggplot( 
  happycleaned, aes(
    x = new_income_range, fill = happy)) + 
  geom_bar(
    position = "stack") + #Creating a stacked bar plot
  theme_minimal() + #Using a simple theme
  theme(axis.text.x=element_text( #Adjusting horizontal axis text to be easily readable
    angle = 60, 
    hjust = 1)) + 
  labs(x = "Financial Satisfaction", #Labeling the axes and fill section
       y = "Frequency",
       fill = "Happiness Response")

```
\newpage
```{r}
#| label: table-hapmarsatfin
#| fig-cap: something2
#| echo: false
#| message: false
hapmarcleaned %>% 
  tbl_cross(row = hapmar, col = satfin, label = list(satfin ~ "Financial Satisfactions", hapmar ~ "Happiness of Marriage"), percent = "column")
```

```{r}
#| label: table-hapmarincome
#| fig-cap: something2
#| echo: false
#| message: false
hapmarcleaned %>% 
  tbl_cross(row = hapmar, col = new_income_range, label = list(new_income_range ~ "Income Ranges", hapmar ~ "Happiness of Marriage"), percent = "column")
```
\newpage
```{r}
#| label: fig-hapmarsatfin
#| fig-cap: something2
#| echo: false
ggplot( 
  hapmarcleaned, aes(
    x = satfin, fill = hapmar)) + 
  geom_bar(
    position = "stack") + #Creating a stacked bar plot
  theme_minimal() + #Using a simple theme
  theme(axis.text.x=element_text( #Adjusting horizontal axis text to be easily readable
    angle = 60, 
    hjust = 1)) + 
  labs(x = "Financial Satisfaction", #Labeling the axes and fill section
       y = "Frequency",
       fill = "Happiness of Marriage")+
  scale_x_discrete(limit = c("Not satisfied at all", "More or less satisfied", "Pretty well satisfied"))
```
\newpage
```{r}
#| label: fig-hapmarincome
#| fig-cap: ???
#| echo: false

ggplot( 
  hapmarcleaned, aes(
    x = new_income_range, fill = hapmar)) + 
  geom_bar(
    position = "stack") + #Creating a stacked bar plot
  theme_minimal() + #Using a simple theme
  theme(axis.text.x=element_text( #Adjusting horizontal axis text to be easily readable
    angle = 60, 
    hjust = 1)) + 
  labs(x = "Financial Satisfaction", #Labeling the axes and fill section
       y = "Frequency",
       fill = "Happiness of Marriage")
```
\newpage
```{r}
#| label: table-healthsatfin
#| fig-cap: something2
#| echo: false
#| message: false
healthcleaned %>% 
  tbl_cross(row = health, col = satfin, label = list(satfin ~ "Financial Satisfactions", health ~ "Quality of Health"), percent = "column")
```

```{r}
#| label: table-healthincome
#| fig-cap: something2
#| echo: false
#| message: false
healthcleaned %>% 
  tbl_cross(row = health, col = new_income_range, label = list(new_income_range ~ "Income Ranges", health ~ "Quality of Health"), percent = "column")
```
\newpage
```{r}
#| label: fig-healthsatfin
#| fig-cap: something2
#| echo: false
ggplot( 
  healthcleaned, aes(
    x = satfin, fill = health)) + 
  geom_bar(
    position = "stack") + #Creating a stacked bar plot
  theme_minimal() + #Using a simple theme
  theme(axis.text.x=element_text( #Adjusting horizontal axis text to be easily readable
    angle = 60, 
    hjust = 1)) + 
  labs(x = "Financial Satisfaction", #Labeling the axes and fill section
       y = "Frequency",
       fill = "Health")+
    scale_x_discrete(limit = c("Not satisfied at all", "More or less satisfied", "Pretty well satisfied"))
```
\newpage
```{r}
#| label: fig-healthincome
#| fig-cap: something2
#| echo: false
ggplot( 
  healthcleaned, aes(
    x = new_income_range, fill = health)) + 
  geom_bar(
    position = "stack") + #Creating a stacked bar plot
  theme_minimal() + #Using a simple theme
  theme(axis.text.x=element_text( #Adjusting horizontal axis text to be easily readable
    angle = 60, 
    hjust = 1)) + 
  labs(x = "Income Ranges", #Labeling the axes and fill section
       y = "Frequency",
       fill = "Health")
```
\newpage
```{r}
#| label: table-finaltsatfin
#| fig-cap: something2
#| echo: false
#| message: false
finaltercleaned %>% 
  tbl_cross(row = finalter, col = new_income_range, label = list(new_income_range ~ "Income Ranges", finalter ~ "Changes in Wealth"), percent = "column")
```

```{r}
#| label: table-finaltincome
#| fig-cap: something2
#| echo: false
#| message: false
finaltercleaned %>% 
  tbl_cross(row = finalter, col = new_income_range, label = list(new_income_range ~ "Income Ranges", finalter ~ "Changes in Wealth"), percent = "column")
```
\newpage
```{r}
#| label: fig-finaltsatfin
#| fig-cap: something2
#| echo: false
ggplot( 
  finaltercleaned, aes(
    x = satfin, fill = finalter)) + 
  geom_bar(
    position = "stack") + #Creating a stacked bar plot
  theme_minimal() + #Using a simple theme
  theme(axis.text.x=element_text( #Adjusting horizontal axis text to be easily readable
    angle = 60, 
    hjust = 1)) + 
  labs(x = "Financial Satisfaction", #Labeling the axes and fill section
       y = "Frequency",
       fill = "Changes in Wealth")+
    scale_x_discrete(limit = c("Not satisfied at all", "More or less satisfied", "Pretty well satisfied"))
```
\newpage
```{r}
#| label: fig-finaltincome
#| fig-cap: something2
#| echo: false
ggplot( 
  finaltercleaned, aes(
    x = new_income_range, fill = finalter)) + 
  geom_bar(
    position = "stack") + #Creating a stacked bar plot
  theme_minimal() + #Using a simple theme
  theme(axis.text.x=element_text( #Adjusting horizontal axis text to be easily readable
    angle = 60, 
    hjust = 1)) + 
  labs(x = "Income Ranges", #Labeling the axes and fill section
       y = "Frequency",
       fill = "Changes in Wealth")
```


# 4 Discussion



## 4.1 Limitations



# 5 Appendix


