---
title: "Well-being of Individuals from the United States Global Social Survey are Affected by Finances, Relationships, and Health"
author: "Justin Abando, Jin Di Liu, Marcin Jaczynski"
thanks: "Code and data are available at: https://github.com/jackchinski/happiness_report"
date: "`r Sys.time()`"
date-format: "D MMMM YYYY"
abstract: "DON'T FORGET THIS"
format: pdf
bibliography: references.bib
---

```{r}
#| include: false

knitr::opts_chunk$set(echo=TRUE)

###Workplace Setup###
library(tidyverse)
library(dplyr)
library(ggplot2)
library(gtsummary)
library(flextable)

quartoclean5 <- read_csv("../../inputs/data/clean5.csv")
mastercleaned <-read_csv("../../outputs/data/master_cleaned.csv")
happycleaned <- read_csv("../../outputs/data/happy_cleaned.csv")
finaltercleaned <-read_csv("../../outputs/data/finalter_cleaned.csv")
hapmarcleaned <- read_csv("../../outputs/data/hapmar_cleaned.csv")
healthcleaned <- read_csv("../../outputs/data/health_cleaned.csv")

```



# 1 Introduction


# 2 Data


## 2.1 Tools Used



## 2.2 Survey Methodology



## 2.3 Survey Biases and Ethics



## 2.4 Data Collection



## 2.5 Data Cleaning



# 3 Results

\newpage
```{r}
#| label: table-satfinincome
#| tbl-cap: Financial Satisfaction vs. Income Ranges
#| echo: false
#| message: false
table_satfinincome <- mastercleaned %>% 
  tbl_cross(row = satfin, col = new_income_range, label = list(new_income_range ~ "Income Ranges", satfin ~ "Financial Satisfaction"), percent = "column") %>% as_flex_table() %>% set_caption(caption = "Financial Satisfaction vs. Income Ranges")

table_satfinincome %>% autofit() %>% fit_to_width(6.5)


```